theme: jekyll-theme-minimal
title: ALife'22 ERA workshop official website
bookmark: 2022 Emerging Researchers in Artificial Life Workshop to be held (<a href="https://www.2022.alife.org/">@ ALife 2022</a>)
